// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtIkY0uQPu9XiY5jzgzpE1qe14KJ-8tAw',
    appId: '1:844491921618:web:a8bb0245b63190821af50b',
    messagingSenderId: '844491921618',
    projectId: 'resume-generator-835e3',
    authDomain: 'resume-generator-835e3.firebaseapp.com',
    storageBucket: 'resume-generator-835e3.appspot.com',
    measurementId: 'G-QREFFQ40SJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJ5gUuBGb5A8PaGl19Vu6p-26TyVqqOSg',
    appId: '1:844491921618:android:7fc57669f9b42cb01af50b',
    messagingSenderId: '844491921618',
    projectId: 'resume-generator-835e3',
    storageBucket: 'resume-generator-835e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8_LhqjVftfF0-m9DgBThKVE0C2CrMtcA',
    appId: '1:844491921618:ios:c65b0467bf8428c51af50b',
    messagingSenderId: '844491921618',
    projectId: 'resume-generator-835e3',
    storageBucket: 'resume-generator-835e3.appspot.com',
    androidClientId: '844491921618-0dki688buikl9fvisn84h0qm417h3392.apps.googleusercontent.com',
    iosClientId: '844491921618-jecormj82tn0sh93220iarcp6maiptmf.apps.googleusercontent.com',
    iosBundleId: 'com.example.test1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8_LhqjVftfF0-m9DgBThKVE0C2CrMtcA',
    appId: '1:844491921618:ios:0acb29656401784e1af50b',
    messagingSenderId: '844491921618',
    projectId: 'resume-generator-835e3',
    storageBucket: 'resume-generator-835e3.appspot.com',
    androidClientId: '844491921618-0dki688buikl9fvisn84h0qm417h3392.apps.googleusercontent.com',
    iosClientId: '844491921618-cqfvba57eah36b78ufo6lmp19omrbfo7.apps.googleusercontent.com',
    iosBundleId: 'com.example.test1.RunnerTests',
  );
}
